### ISSUE TITLE
Pass aws credentials to aws.DynamoDB() instead of using aws.config .update

### ISSUE THREAD

**Issue by liamqma** [victorquinn/dynasty#49]
Hi 

On line https://github.com/victorquinn/dynasty/blob/master/src/dynasty.coffee#L35, can we do

```
this.dynamo = new aws.DynamoDB(credentials);
``` 

Instead of
```
aws.config.update(credentials);
``` 

Because I will pass 'http://localhost:8000' as endpoint to dynasty in my local development, however I use other AWS services e.g., KMS and SES. All these services are going to share same endpoint which is 'localhost:8000'

**Comment by victorquinn** [comment]
Absolutely, that sounds like a good improvement!

**Comment by kartiklad** [comment]
Stuck with a similar issue. I use KMS and DynamoDB and want to test these services locally but since Dynasty updates the global config, I need to pass endpoints to every single service instance when testing locally. 

Would be great if this issue could be solved with a quick fix.

Thanks @liamqma for pointing out the issue!

**Comment by liamqma** [comment]
Hi Victor,

I just created a pull request. Can you have a look if it's okay please? 

https://github.com/victorquinn/dynasty/pull/50

Thanks!
